package dat.config;

import dat.entities.*;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;

public class Populate {

    public static void main(String[] args) {
        // Opret en instans af Populate-klassen og kald populateDatabase()
//        Populate populate = new Populate();
        populateDatabase();
    }

    // Metode til at populere databasen med cykler og komponenter
    public static void populateDatabase() {
        EntityManagerFactory emf = HibernateConfig.getEntityManagerFactory();

        // Opret rammer
        Frame frame1 = new Frame("De Rosa", "838 Disc", "Carbon", "Disc", 1270, 56);
        Frame frame2 = new Frame("Argon 18", "Nitrogen Pro", "Carbon", "Rim", 1400, 52);
        Frame frame3 = new Frame("Argon 18", "Gallium", "Aluminium", "Disc", 1700, 56);
        Frame frame4 = new Frame("Argon 18", "Gallium Pro", "Carbon", "Rim", 1350, 55);
        Frame frame5 = new Frame("Argon 18", "Krypton X", "Carbon", "Rim", 1550, 56);
        Frame frame6 = new Frame("BH", "G7 Disc", "Carbon", "Disc", 1350, 54);
        Frame frame7 = new Frame("BH", "G8 Pro", "Carbon", "Disc", 1300, 56);
        Frame frame8 = new Frame("Bianchi", "Intenso Disc", "Aluminium", "Disc", 1600, 56);
        Frame frame9 = new Frame("Bianchi", "Oltre XR4", "Carbon", "Disc", 1350, 56);
        Frame frame10 = new Frame("BMC", "Teammachine SLR", "Carbon", "Disc", 1300, 56);
        Frame frame11 = new Frame("BMC", "Roadmachine 01", "Carbon", "Disc", 1350, 56);
        Frame frame12 = new Frame("Cannondale", "Synapse Carbon", "Carbon", "Disc", 1450, 56);
        Frame frame13 = new Frame("Cannondale", "SystemSix Carbon", "Carbon", "Disc", 1310, 56);
        Frame frame14 = new Frame("Cannondale", "CAAD13", "Aluminium", "Disc", 1350, 56);
        Frame frame15 = new Frame("Cannondale", "CAAD Optimo", "Aluminium", "Disc", 1450, 56);
        Frame frame16 = new Frame("Cannondale", "Supersix EVO", "Carbon", "Disc", 1300, 56);
        Frame frame17 = new Frame("Canyon", "Aeroad CF SLX", "Carbon", "Disc", 1521, 56);
        Frame frame18 = new Frame("Canyon", "Endurace CF SLX", "Carbon", "Rim", 1400, 58);
        Frame frame19 = new Frame("Canyon", "Aeroad CF SLX", "Carbon", "Disc", 1450, 52);
        Frame frame20 = new Frame("Canyon", "Ultimate AL Disc", "Aluminium", "Disc", 1300, 58);
        Frame frame21 = new Frame("Canyon", "Endurace CFR", "Carbon", "Disc", 1550, 56);
        Frame frame22 = new Frame("Canyon", "Aeroad AL Disc", "Aluminium", "Disc", 1400, 56);
        Frame frame23 = new Frame("Canyon", "Endurace CF SL", "Carbon", "Disc", 1400, 56);
        Frame frame24 = new Frame("Canyon", "Ultimate CF SLX", "Carbon", "Disc", 1355, 56);
        Frame frame25 = new Frame("Cervelo", "R5", "Carbon", "Disc", 1500, 56);
        Frame frame26 = new Frame("Cervelo", "R3 Disc", "Carbon", "Disc", 1450, 58);
        Frame frame27 = new Frame("Cervelo", "Caledonia", "Carbon", "Disc", 1500, 57);
        Frame frame28 = new Frame("Colnago", "C64", "Carbon", "Disc", 1400, 58);
        Frame frame29 = new Frame("Colnago", "C64", "Carbon", "Rim", 1350, 58);
        Frame frame30 = new Frame("De Rosa", "Merak", "Carbon", "Disc", 1270, 56);
        Frame frame31 = new Frame("Felt", "FR2", "Carbon", "Rim", 1250, 56);
        Frame frame32 = new Frame("Felt", "VR3", "Carbon", "Disc", 1250, 54);
        Frame frame33 = new Frame("Focus", "Izalco Max", "Carbon", "Disc", 1300, 56);
        Frame frame34 = new Frame("Focus", "Paralane", "Carbon", "Disc", 1300, 55);
        Frame frame35 = new Frame("Fuji", "SL 1.1", "Carbon", "Rim", 1450, 56);
        Frame frame36 = new Frame("Giant", "TCR Advanced Pro", "Carbon", "Rim", 1250, 56);
        Frame frame37 = new Frame("Giant", "Defy Advanced Pro", "Carbon", "Disc", 1300, 56);
        Frame frame38 = new Frame("Kona", "Rove DL", "Steel", "Disc", 1700, 57);
        Frame frame39 = new Frame("Look", "795 Aerolight", "Carbon", "Disc", 1400, 58);
        Frame frame40 = new Frame("Look", "785 Huez", "Carbon", "Disc", 1400, 55);
        Frame frame41 = new Frame("Marin", "Gestalt X10", "Aluminium", "Disc", 1500, 55);
        Frame frame42 = new Frame("Merida", "Scultura", "Aluminium", "Rim", 1600, 54);
        Frame frame43 = new Frame("Merida", "Reacto", "Carbon", "Rim", 1500, 58);
        Frame frame44 = new Frame("Olmo", "Racing Aluminium", "Aluminium", "Rim", 1600, 54);
        Frame frame45 = new Frame("Orbea", "Orca M21e", "Carbon", "Disc", 1300, 58);
        Frame frame46 = new Frame("Orbea", "Avant M20", "Aluminium", "Rim", 1600, 57);
        Frame frame47 = new Frame("Pinarello", "Dogma F12", "Carbon", "Disc", 1200, 58);
        Frame frame48 = new Frame("Pinarello", "Prince", "Carbon", "Rim", 1550, 54);
        Frame frame49 = new Frame("Raleigh", "Aero 700", "Aluminium", "Rim", 1650, 54);
        Frame frame50 = new Frame("Ridley", "Fenix SL", "Carbon", "Disc", 1400, 57);
        Frame frame51 = new Frame("Ridley", "Helium SLX", "Carbon", "Rim", 1450, 58);
        Frame frame52 = new Frame("Ritchey", "SwissCross", "Steel", "Rim", 1700, 58);
        Frame frame53 = new Frame("Ritchey", "Road Logic", "Steel", "Rim", 1700, 54);
        Frame frame54 = new Frame("Scott", "Addict RC Ultimate HMX SL", "Carbon", "Disc", 925, 55);
        Frame frame55 = new Frame("Scott", "Foil RC Ultimate HMX SL", "Carbon", "Disc", 1410, 56);
        Frame frame79 = new Frame("Scott", "Addict RC Pro HMX SL", "Carbon", "Disc", 990, 55);
        Frame frame80 = new Frame("Scott", "Foil RC Disc", "Carbon", "Disc", 1460, 56);
        Frame frame81 = new Frame("Scott", "Addict RC HMX Flatmount Disc", "Carbon", "Disc", 990, 55);
        Frame frame82 = new Frame("Scott", "Addict Disc HMF ", "Carbon", "Disc", 1220, 56);
        Frame frame56 = new Frame("Specialized", "S-Works Tarmac", "Titanium", "Rim", 1600, 55);
        Frame frame57 = new Frame("Specialized", "Roubaix Pro", "Carbon", "Disc", 1450, 56);
        Frame frame58 = new Frame("Specialized", "S-Works Venge", "Carbon", "Disc", 1400, 54);
        Frame frame59 = new Frame("Specialized", "Allez Sprint", "Aluminium", "Rim", 1200, 56);
        Frame frame60 = new Frame("Specialized", "Diverge Pro", "Carbon", "Disc", 1350, 58);
        Frame frame61 = new Frame("Specialized", "Tarmac SL7", "Carbon", "Rim", 1500, 52);
        Frame frame62 = new Frame("Specialized", "Roubaix Sport", "Carbon", "Disc", 1300, 58);
        Frame frame63 = new Frame("Specialized", "Turbo Levo SL", "Aluminium", "Disc", 1600, 54);
        Frame frame64 = new Frame("Time", "Alpe D'Huez 01", "Carbon", "Rim", 1350, 55);
        Frame frame65 = new Frame("Trek", "500 Series OCLV Carbon","Carbon", "Disc", 1500, 56);
        Frame frame66 = new Frame("Trek", "Emonda SLR 9", "Carbon", "Disc", 1300, 56);
        Frame frame67 = new Frame("Trek", "Madone SL 6", "Carbon", "Disc", 1550, 56);
        Frame frame68 = new Frame("Wilier", "Cento 10 NDR", "Carbon", "Rim", 1450, 58);
        Frame frame69 = new Frame("Wilier", "Zero SLR", "Carbon", "Disc", 1350, 56);
        Frame frame70 = new Frame("Wilier", "Centos 10", "Carbon", "Rim", 1500, 58);
        Frame frame71 = new Frame("Giant", "ALUXX-Grade", "Aluminum", "Rim", 1250, 56);
        Frame frame72 = new Frame("Cervelo", "All-Carbon Tapered", "Carbon", "Disc", 1500, 56);
        Frame frame73 = new Frame("Pinarello", "Dogma F10", "Carbon", "Disc", 1200, 58);
        Frame frame74 = new Frame("Colnago", "V3Rs", "Carbon", "Disc", 1400, 58);
        Frame frame75 = new Frame("De Rosa", "Settanta", "Carbon", "Disc", 1010, 54);
        Frame frame76 = new Frame("De Rosa", "Merak", "Carbon", "Disc", 1290, 56);
        Frame frame77 = new Frame("De Rosa", "Idol Disc", "Carbon", "Disc", 1370, 56);
        Frame frame78 = new Frame("Colnago", "C 64", "Carbon", "Disc", 1140, 56);






        // Opret saddel
        Saddle saddle1 = new Saddle("Fi'zi:k", "Synthetic", "Arione Classic", 225, 130);
        Saddle saddle2 = new Saddle("Selle Italia", "Foam", "Flite Boost TM Superflow", 233, 135);
        Saddle saddle3 = new Saddle("Selle Italia", "Leather", "Flite", 300, 155);
        Saddle saddle4 = new Saddle("Specialized", "Foam", "Power", 250, 143);
        Saddle saddle5 = new Saddle("Prologo", "Foam", "Dimension", 220, 145);
        Saddle saddle6 = new Saddle("Fabric", "Synthetic", "Scoop", 180, 130);
        Saddle saddle7 = new Saddle("Giant", "Synthetic", "Contact", 160, 145);
        Saddle saddle8 = new Saddle("Trek", "Synthetic", "Bontrager Ajna", 200, 138);
        Saddle saddle9 = new Saddle("ISM", "Foam", "PN 3.0", 250, 130);
        Saddle saddle10 = new Saddle("Selle Royal", "Synthetic", "Lookin", 100, 150);
        Saddle saddle11 = new Saddle("Fi'zi:k", "Synthetic", "Vento Argo R3", 213, 140);
        Saddle saddle12 = new Saddle("Ritchey", "Foam", "WCS", 220, 142);
        Saddle saddle13 = new Saddle("Terry", "Synthetic", "Butterfly", 240, 150);
        Saddle saddle14 = new Saddle("Selle Italia", "Foam", "X3", 150, 145);
        Saddle saddle15 = new Saddle("Selle San Marco", "Leather", "Regale", 260, 145);
        Saddle saddle16 = new Saddle("SDG", "Synthetic", "Fly", 220, 145);
        Saddle saddle17 = new Saddle("Bontrager", "Synthetic", "Aeolus", 200, 142);
        Saddle saddle18 = new Saddle("WTB", "Synthetic", "Volt", 180, 140);
        Saddle saddle19 = new Saddle("Ergon", "Synthetic", "SME3", 160, 145);
        Saddle saddle20 = new Saddle("SQlab", "Synthetic", "611", 190, 140);
        Saddle saddle21 = new Saddle("Fabric", "Synthetic", "Line", 170, 145);
        Saddle saddle22 = new Saddle("Prologo", "Synthetic", "Nago", 150, 140);
        Saddle saddle23 = new Saddle("Selle Italia", "Synthetic", "SLR", 200, 145);
        Saddle saddle24 = new Saddle("Fi'zi:k", "Synthetic", "Vento Antares R5", 210, 140);
        Saddle saddle25 = new Saddle("Brooks", "Leather", "Cambium", 250, 160);
        Saddle saddle26 = new Saddle("Selle Royal", "Foam", "Freeway", 120, 150);
        Saddle saddle27 = new Saddle("Giant", "Leather", "Fleet", 230, 145);
        Saddle saddle28 = new Saddle("Specialized", "Synthetic", "Henge", 200, 150);
        Saddle saddle29 = new Saddle("Fi'zi:k", "Synthetic", "Antares 00", 140, 145);
        Saddle saddle30 = new Saddle("Selle Italia", "Carbon", "SLR Tekno", 400, 130);
        Saddle saddle31 = new Saddle("Bontrager", "Synthetic", "H1", 180, 138);
        Saddle saddle32 = new Saddle("Selle Italia", "Foam", "SLR TM", 233, 131);
        Saddle saddle33 = new Saddle("Ritchey", "Carbon", "Comp", 240, 140);
        Saddle saddle34 = new Saddle("Fi'zi:k", "Synthetic", "Arione 00", 140, 124);
        Saddle saddle35 = new Saddle("Brooks", "Leather", "Swift", 300, 160);
        Saddle saddle36 = new Saddle("Colnago", "Foam", "Prologo X10", 230, 145);
        Saddle saddle37 = new Saddle("Fabric", "Synthetic", "Shallow", 180, 130);
        Saddle saddle38 = new Saddle("SQlab", "Synthetic", "612", 200, 140);
        Saddle saddle39 = new Saddle("Selle San Marco", "Synthetic", "Concor", 250, 145);
        Saddle saddle40 = new Saddle("ISM", "Leather", "PL 1.1", 300, 130);
        Saddle saddle41 = new Saddle("Bontrager", "Foam", "Verse Comp", 307, 155);
        Saddle saddle42 = new Saddle("Selle Italia", "Synthetic", "SLR Boost Superflow Kit", 120, 130);
        Saddle saddle43 = new Saddle("De Rosa", "Foam", "X-flow", 250, 145);
        Saddle saddle44 = new Saddle("Fi'zi:k", "Foam", "Vento Antares R3 Adaptive", 220, 140);
        Saddle saddle45 = new Saddle("Fi'zi:k", "Foam", "Vento Antares R1 Adaptive", 180, 140);
        Saddle saddle46 = new Saddle("Fi'zi:k", "Foam", "Vento Antares R3", 195, 140);
        Saddle saddle47 = new Saddle("Fi'zi:k", "Foam", "Vento Antares R1", 161, 140);
        Saddle saddle48 = new Saddle("Fi'zi:k", "Foam", "Tempo Aliante R5", 230, 145);
        Saddle saddle49 = new Saddle("Fi'zi:k", "Foam", "Tempo Aliante R3", 220, 145);
        Saddle saddle50 = new Saddle("Fi'zi:k", "Foam", "Tempo Aliante R1", 180, 145);
        Saddle saddle51 = new Saddle("Fi'zi:k", "Foam", "Vento Argo 00 Adaptive", 175, 140);
        Saddle saddle52 = new Saddle("Fi'zi:k", "Foam", "Vento Argo R3 Adaptive", 224, 140);
        Saddle saddle53 = new Saddle("Fi'zi:k", "Foam", "Vento Argo R1 Adaptive", 190, 140);
        Saddle saddle54 = new Saddle("Fi'zi:k", "Foam", "Vento Argo 00", 134, 140);
        Saddle saddle55 = new Saddle("Fi'zi:k", "Foam", "Antares Versus Evo R3 Adaptive", 217, 139);
        Saddle saddle56 = new Saddle("Fi'zi:k", "Foam", "Antares Versus Evo R1 Adaptive", 180, 139);
        Saddle saddle57 = new Saddle("Fi'zi:k", "Foam", "Tempo Argo R3 Les Classiques", 229, 150);
        Saddle saddle58 = new Saddle("Fi'zi:k", "Foam", "Tempo Argo R5", 241, 150);
        Saddle saddle59 = new Saddle("Fi'zi:k", "Foam", "Tempo Argo R3", 229, 150);
        Saddle saddle60 = new Saddle("Fi'zi:k", "Foam", "Tempo Argo R1", 195, 150);
        Saddle saddle61 = new Saddle("Fi'zi:k", "Foam", "Vento Argo R5", 225, 140);
        Saddle saddle62 = new Saddle("Fi'zi:k", "Foam", "Vento Argo R1", 179, 140);
        Saddle saddle63 = new Saddle("Fi'zi:k", "Foam", "Arione R3 Open", 230, 132);
        Saddle saddle64 = new Saddle("Fi'zi:k", "Foam", "Arione R1 Open", 199, 132);
        Saddle saddle65 = new Saddle("Fi'zi:k", "Foam", "Arione R3 Open White", 230, 132);
        Saddle saddle66 = new Saddle("Fi'zi:k", "Foam", "Arione R1 Versus Evo", 185, 130);
        Saddle saddle67 = new Saddle("Fi'zi:k", "Foam", "Arione R3", 200, 126);
        Saddle saddle68 = new Saddle("Fi'zi:k", "Foam", "Aliante R3 Open White", 235, 141);
        Saddle saddle69 = new Saddle("Fi'zi:k", "Foam", "Antares R3 Open White", 215, 141);
        Saddle saddle70 = new Saddle("Fi'zi:k", "Foam", "Antares R1 Open", 180, 145);
        Saddle saddle71 = new Saddle("Fi'zi:k", "Foam", "Antares R3 Versus Evo", 215, 139);
        Saddle saddle72 = new Saddle("Fi'zi:k", "Foam", "Antares R1 Versus Evo", 179, 140);
        Saddle saddle73 = new Saddle("Fi'zi:k", "Foam", "Antares 00 Versus Evo", 153, 139);
        Saddle saddle74 = new Saddle("Fi'zi:k", "Foam", "Antares R3", 200, 141);
        Saddle saddle75 = new Saddle("Fi'zi:k", "Foam", "Arione R1", 163, 126);
        Saddle saddle76 = new Saddle("Fi'zi:k", "Foam", "Antares R1", 165, 152);
        Saddle saddle77 = new Saddle("Selle Italia", "Foam", "SLR Boost 3D Kit Carbonio", 166, 130);
        Saddle saddle78 = new Saddle("Selle Italia", "Foam", "Novus Boost Evo 3D Kit Carbonio", 210, 145);
        Saddle saddle79 = new Saddle("Selle Italia", "Foam", "SLR Boost Tekno", 95, 130);
        Saddle saddle80 = new Saddle("Selle Italia", "Foam", "SLR Boost 3D Ti 316 Superslow", 200, 130);
        Saddle saddle81 = new Saddle("Selle Italia", "Foam", "Novus Boost Evo 3D Ti 316 Superslow", 246, 145);
        Saddle saddle82 = new Saddle("Selle Italia", "Foam", "SLR Boost Kit Carbonio Superslow", 122, 130);
        Saddle saddle83 = new Saddle("Selle Italia", "Foam", "SLR Boost Kit Carbonio", 136, 130);
        Saddle saddle84 = new Saddle("Selle Italia", "Foam", "SLR Boost Pro Team Kit Carbonio Superslow", 137, 130);
        Saddle saddle85 = new Saddle("Selle Italia", "Foam", "Flite Boost Pro Team Kit Carbonio Superslow", 165, 135);
        Saddle saddle86 = new Saddle("Selle Italia", "Foam", "SLR Kit Carbonio Superslow", 148, 131);
        Saddle saddle87 = new Saddle("Selle Italia", "Foam", "SLR Kit Carbonio", 122, 131);
        Saddle saddle88 = new Saddle("Selle Italia", "Foam", "Flite Boost Pro Team Kit Carbonio Superslow", 165, 135);
        Saddle saddle89 = new Saddle("Selle Italia", "Foam", "Flite Boost Kit Carbonio Superslow MVDP", 162, 145);
        Saddle saddle90 = new Saddle("Selle Italia", "Foam", "Flite Boost Kit Carbonio Superslow", 157, 135);
        Saddle saddle91 = new Saddle("Selle Italia", "Foam", "Flite Boost Kit Carbonio", 173, 135);
        Saddle saddle92 = new Saddle("Selle Italia", "Foam", "Flite Boost TM", 247, 135);
        Saddle saddle93 = new Saddle("Selle Italia", "Foam", "SLR Boost TI 315 Superslow", 158, 130);
        Saddle saddle94 = new Saddle("Selle Italia", "Foam", "SLR Boost Endurance TI 316 Superslow", 202, 130);
        Saddle saddle95 = new Saddle("Selle Italia", "Foam", "SLR TI 316 Superslow", 185, 130);
        Saddle saddle96 = new Saddle("Selle Italia", "Foam", "Flite Boost TI 316 Superslow", 194, 135);
        Saddle saddle97 = new Saddle("Selle Italia", "Foam", "Novus Boost Evo TI 316 Superslow", 200, 145);
        Saddle saddle98 = new Saddle("Selle Italia", "Foam", "Novus Endurance TI 316 Superslow", 288, 138);
        Saddle saddle99 = new Saddle("Selle Italia", "Foam", "SLR Boost TM Superslow", 208, 130);
        Saddle saddle100 = new Saddle("Selle Italia", "Foam", "SLR Boost TM", 230, 130);
        Saddle saddle101 = new Saddle("Selle Italia", "Foam", "SLR TM Superslow", 205, 131);
        Saddle saddle102 = new Saddle("Syncros", "Foam", "Syncros Belcarra R 1.0 NEO", 200, 130);
        Saddle saddle103 = new Saddle("Syncros", "Foam", "Syncros Belcarra V 1.5 NEO", 230, 145);
        Saddle saddle104 = new Saddle("Syncros", "Foam", "Syncros Belcarra V 2.0 NEO", 260, 145);
        Saddle saddle105 = new Saddle("Syncros", "Foam", "Syncros Tofino R SL", 148, 135);
        Saddle saddle106 = new Saddle("Syncros", "Foam", "Syncros Tofino V SL", 156, 145);
        Saddle saddle107 = new Saddle("Syncros", "Foam", "Syncros Belcarra R 1.0", 200, 130);
        Saddle saddle108 = new Saddle("Syncros", "Foam", "Syncros Belcarra V 1.0", 160, 140);
        Saddle saddle109 = new Saddle("Syncros", "Foam", "Syncros Belcarra V 1.0 TRI", 220, 130);
        Saddle saddle110 = new Saddle("Syncros", "Carbon", "Syncros Belcarra Carbon RR", 120, 130);
        Saddle saddle111 = new Saddle("Syncros", "Carbon", "Syncros Belcarra R 1.0 Carbon Cutout", 140, 125);
        Saddle saddle112 = new Saddle("Syncros", "Foam", "Syncros Tofino R 2.0", 240, 135);
        Saddle saddle113 = new Saddle("Syncros", "Foam", "Syncros Belcarra R SL NEO", 170, 128);
        Saddle saddle114 = new Saddle("Syncros", "Foam", "Syncros Belcarra R 2.0", 250, 135);
        Saddle saddle115 = new Saddle("Syncros", "Foam", "Syncros Belcarra V 2.0 Cutout", 260, 140);
        Saddle saddle116 = new Saddle("Syncros", "Foam", "Syncros Tofino V 1.0", 165, 140);
        Saddle saddle117 = new Saddle("Syncros", "Foam", "Syncros Tofino V 1.5", 180, 145);




        // Opret hjul med modeller
        Wheel wheel1 = new Wheel("Zipp", "Carbon", "Disc", "Zipp 404 Firecrest", 1559, 23);
        Wheel wheel2 = new Wheel("Shimano", "Carbon", "Disc", "Shimano WH-R9270-C36", 1154, 21);
        Wheel wheel3 = new Wheel("DT Swiss", "Carbon", "Disc", "DT Swiss PRC 1400", 1600, 28);
        Wheel wheel4 = new Wheel("Fulcrum", "Aluminium", "Disc", "Fulcrum Racing 3", 1660, 19);
        Wheel wheel5 = new Wheel("Campagnolo", "Carbon", "Disc", "Campagnolo Shamal", 1585, 21);
        Wheel wheel6 = new Wheel("Shimano", "Aluminium", "Rim", "Shimano WH-RS100", 900, 20);
        Wheel wheel7 = new Wheel("Reynolds", "Carbon", "Disc", "Reynolds Blacklabel 80 Pro", 1625, 21);
        Wheel wheel8 = new Wheel("Easton", "Carbon", "Disc", "Easton EC90 Aero 55", 1545, 19);
        Wheel wheel9 = new Wheel("Hunt", "Carbon", "Rim", "Hunt 50 Carbon Wide Aero", 1537, 19);
        Wheel wheel10 = new Wheel("Hunt", "Carbon", "Rim", "Hunt 44 Aero Carbon Disc", 1466, 20);
        Wheel wheel11 = new Wheel("HED", "Carbon", "Rim", "HED Belgium Plus R45", 1639, 20);
        Wheel wheel12 = new Wheel("Roval", "Carbon", "Disc", "CLX 32", 1600, 25);
        Wheel wheel13 = new Wheel("Easton", "Carbon", "Disc", "Easton EC90 SL Disc", 1485, 19);
        Wheel wheel14 = new Wheel("Deda", "Aluminium", "Rim", "Deda SL3", 1200, 22);
        Wheel wheel15 = new Wheel("Spinergy", "Carbon", "Disc", "FCC 32", 1597, 18);
        Wheel wheel16 = new Wheel("Reynolds", "Carbon", "Disc", "Blacklabel 25 Pro", 1251, 21);
        Wheel wheel17 = new Wheel("Bora", "Carbon", "Rim", "Bora One 35 Disc", 1483, 25);
        Wheel wheel18 = new Wheel("Fulcrum", "Aluminium", "Rim", "Fulcrum Racing 5", 1660, 20);
        Wheel wheel19 = new Wheel("Shimano", "Carbon", "Disc", "Shimano WH-RS710-C46", 1612, 21);
        Wheel wheel20 = new Wheel("Campagnolo", "Aluminium", "Rim", "Campagnolo Zonda", 1540, 22);
        Wheel wheel21 = new Wheel("Shimano", "Carbon", "Disc", "Shimano WH-R9270-C50", 1333, 21);
        Wheel wheel22 = new Wheel("DT Swiss", "Aluminium", "Rim", "DT Swiss M 1900", 1350, 24);
        Wheel wheel23 = new Wheel("Zipp", "Carbon", "Disc", "Zipp 303 Firecrest", 1372, 21);
        Wheel wheel24 = new Wheel("Fulcrum", "Carbon", "Disc", "Fulcrum Racing 4", 1870, 22);
        Wheel wheel25 = new Wheel("Shimano", "Carbon", "Disc", "Shimano WH-RS710-C32", 1504, 21);
        Wheel wheel26 = new Wheel("Fulcrum", "Aluminium", "Rim", "Fulcrum Racing Zero", 1490, 23);
        Wheel wheel27 = new Wheel("Easton", "Carbon", "Disc", "Easton EC90 Aero 85 Disc", 1827, 19);
        Wheel wheel28 = new Wheel("Syncros", "Carbon", "Rim", "Syncros 1.0 Aero", 1450, 25);
        Wheel wheel29 = new Wheel("Shimano", "Carbon", "Disc", "Shimano WH-R8170-C60", 1649, 21);
        Wheel wheel30 = new Wheel("HED", "Aluminium", "Rim", "HED Jet RC4", 1605, 24);
        Wheel wheel31 = new Wheel("Shimano", "Carbon", "Disc", "Shimano WH-R8170-C50", 1570, 21);
        Wheel wheel32 = new Wheel("Campagnolo", "Aluminium", "Disc", "Campagnolo Zonda Disc", 1675, 22);
        Wheel wheel33 = new Wheel("Reynolds", "Carbon", "Disc", "Reynolds Blacklabel 46 Expert", 1397, 21);
        Wheel wheel34 = new Wheel("Zipp", "Carbon", "Disc", "Zipp 303 S Firecrest", 1530, 23);
        Wheel wheel35 = new Wheel("Spinergy", "Carbon", "Disc", "Spinergy FCC 47", 1794, 23);
        Wheel wheel36 = new Wheel("Fulcrum", "Carbon", "Rim", "Fulcrum Racing 6", 1550, 27);
        Wheel wheel37 = new Wheel("Shimano", "Aluminium", "Rim", "Shimano WH-RS500", 1649, 15);
        Wheel wheel38 = new Wheel("Shimano", "Carbon", "Disc", "Shimano WH-R9270-C60", 1437, 21);
        Wheel wheel39 = new Wheel("DT Swiss", "Carbon", "Disc", "DT Swiss EX 1501", 1750, 30);
        Wheel wheel40 = new Wheel("Zipp", "Aluminium", "Rim", "Zipp 302", 1400, 22);
        Wheel wheel41 = new Wheel("Bontrager", "Aluminium", "Rim", "Bontrager Paradigm Comp 25", 1400, 25);
        Wheel wheel42 = new Wheel("Fulcrum", "Carbon", "Disc", "Fulcrum Sharq", 1440, 25);
        Wheel wheel43 = new Wheel("Fulcrum", "Carbon", "Disc", "Fulcrum Speed 42", 1410, 23);
        Wheel wheel44 = new Wheel("Fulcrum", "Carbon", "Disc", "Fulcrum Racing Wind 42", 1510, 23);
        Wheel wheel45 = new Wheel("Fulcrum", "Carbon", "Disc", "Fulcrum Racing Wind 57", 1585, 23);
        Wheel wheel46 = new Wheel("Fulcrum", "Aluminium", "Disc", "Fulcrum Racing 6", 1780, 20);
        Wheel wheel47 = new Wheel("Fulcrum", "Aluminium", "Disc", "Fulcrum Rapid Red 5", 1760, 23);
        Wheel wheel48 = new Wheel("Spinergy", "Carbon", "Disc", "Spinergy ZTL Aero Bladed", 1415, 23);
        Wheel wheel49 = new Wheel("Spinergy", "Carbon", "Disc", "Spinergy FCC 47", 1590, 23);
        Wheel wheel50 = new Wheel("Spinergy", "Aluminium", "Disc", "Spinergy GX32", 1695, 19);
        Wheel wheel51 = new Wheel("Deda", "Carbon", "Disc", "Deda SL4", 1520, 19);
        Wheel wheel52 = new Wheel("DT Swiss", "Carbon", "Disc", "DT Swiss ARC 1100", 1292, 28);
        Wheel wheel53 = new Wheel("DT Swiss", "Aluminium", "Disc", "DT Swiss E 1900", 1390, 25);
        Wheel wheel54 = new Wheel("DT Swiss", "Carbon", "Disc", "DT Swiss ARC 1400", 1371, 25);
        Wheel wheel55 = new Wheel("DT Swiss", "Aluminium", "Disc", "DT Swiss AR 1600 Spline", 1657, 25);
        Wheel wheel56 = new Wheel("DT Swiss", "Aluminium", "Disc", "DT Swiss AR 1800 Spline", 1691, 25);
        Wheel wheel57 = new Wheel("DT Swiss", "Carbon", "Rim", "DT Swiss PRC 1400 Spline", 1486, 25);
        Wheel wheel58 = new Wheel("DT Swiss", "Aluminium", "Disc", "DT Swiss PR 1600 Spline", 1565, 25);
        Wheel wheel59 = new Wheel("DT Swiss", "Aluminium", "Disc", "DT Swiss P 1800 Spline", 1590, 25);
        Wheel wheel60 = new Wheel("Bora", "Carbon", "Disc", "Bora WTO 60", 1460, 23);
        Wheel wheel61 = new Wheel("Bora", "Carbon", "Disc", "Bora WTO 45", 1405, 23);
        Wheel wheel62 = new Wheel("Bora", "Carbon", "Disc", "Bora WTO 35", 1370, 23);
        Wheel wheel63 = new Wheel("Bora", "Carbon", "Disc", "Bora Ultra WTO 60", 1395, 23);
        Wheel wheel64 = new Wheel("Bora", "Carbon", "Disc", "Bora Ultra WTO 45", 1325, 23);
        Wheel wheel65 = new Wheel("Bora", "Carbon", "Disc", "Bora Ultra WTO 35", 1285, 23);
        Wheel wheel66 = new Wheel("Bora", "Carbon", "Disc", "Bora Hyperon Ultra", 1240, 21);
        Wheel wheel67 = new Wheel("Bora", "Carbon", "Disc", "Bora Hyperon", 1340, 21);
        Wheel wheel68 = new Wheel("Bora", "Carbon", "Disc", "Bora Ultra WTO 33", 1385, 21);
        Wheel wheel69 = new Wheel("Bora", "Carbon", "Disc", "Bora WTO 33", 1485, 19);
        Wheel wheel70 = new Wheel("Bora", "Carbon", "Rim", "Bora WTO 60", 1547, 19);
        Wheel wheel71 = new Wheel("Bora", "Carbon", "Rim", "Bora WTO 45", 1496, 19);
        Wheel wheel72 = new Wheel("Bora", "Carbon", "Rim", "Bora WTO 33", 1395, 19);
        Wheel wheel73 = new Wheel("Bora", "Carbon", "Disc", "Bora Ultra WTO 80", 1590, 21);
        Wheel wheel74 = new Wheel("Campagnolo", "Aluminium", "Disc", "Campagnolo Scirocco Disc", 1740, 19);
        Wheel wheel75 = new Wheel("Campagnolo", "Aluminium", "Rim", "Campagnolo Scirocco", 1950, 22);
        Wheel wheel76 = new Wheel("Roval", "Carbon", "Disc", "Roval Terra C", 1610, 25);
        Wheel wheel77 = new Wheel("Roval", "Carbon", "Disc", "Roval Terra CLX II", 1250, 25);
        Wheel wheel78 = new Wheel("Roval", "Carbon", "Disc", "Roval Terra CL", 1408, 25);
        Wheel wheel79 = new Wheel("Roval", "Aluminium", "Disc", "Roval Alpinist CLX", 1485, 20);
        Wheel wheel80 = new Wheel("Roval", "Carbon", "Disc", "Roval Alpinist CLX II", 1265, 21);
        Wheel wheel81 = new Wheel("Roval", "Carbon", "Disc", "Roval Alpinist CL II", 1375, 21);
        Wheel wheel82 = new Wheel("Roval", "Carbon", "Disc", "Roval Rapide C 38", 1600, 21);
        Wheel wheel83 = new Wheel("Roval", "Carbon", "Disc", "Roval Rapide CL II", 1590, 21);
        Wheel wheel84 = new Wheel("Roval", "Carbon", "Disc", "Roval Rapide CLX II", 1520, 21);
        Wheel wheel85 = new Wheel("Zipp", "Carbon", "Disc", "Zipp 454 NSW", 1428, 23);
        Wheel wheel86 = new Wheel("Zipp", "Carbon", "Disc", "Zipp 858 NSW", 1530, 23);
        Wheel wheel87 = new Wheel("Zipp", "Carbon", "Disc", "Zipp 808 Firecrest", 1635, 23);
        Wheel wheel88 = new Wheel("Zipp", "Carbon", "Disc", "Zipp 353 NSW", 1308, 25);
        Wheel wheel89 = new Wheel("Shimano", "Carbon", "Disc", "Shimano WH-R8170-C36", 1488, 21);
        Wheel wheel90 = new Wheel("Zipp", "Carbon", "Disc", "Zipp 303 Firecrest 650B", 1520, 21);
        Wheel wheel91 = new Wheel("Mavic", "Aluminium", "Disc", "Mavic Ksyrium SL Disc", 1575, 19);
        Wheel wheel92 = new Wheel("Mavic", "Aluminium", "Disc", "Mavic Ksyrium 30 Disc", 1796, 19);
        Wheel wheel93 = new Wheel("Mavic", "Aluminium", "Disc", "Mavic Aksium Disc", 1905, 17);
        Wheel wheel94 = new Wheel("Mavic", "Aluminium", "Rim", "Mavic Ksyrium SL", 1480, 19);
        Wheel wheel95 = new Wheel("Mavic", "Aluminium", "Rim", "Mavic Aksium", 1840, 17);
        Wheel wheel96 = new Wheel("Mavic", "Carbon", "Disc", "Mavic Cosmic Ultimate 45 Disc", 1255, 19);
        Wheel wheel97 = new Wheel("Mavic", "Carbon", "Disc", "Mavic Cosmic SLR 65 Disc", 1620, 19);
        Wheel wheel98 = new Wheel("Mavic", "Carbon", "Disc", "Mavic Cosmic SLR 45 Disc", 1482, 23);
        Wheel wheel99 = new Wheel("Mavic", "Carbon", "Disc", "Mavic Cosmic SLR 32 Disc", 1390, 21);
        Wheel wheel100 = new Wheel("Mavic", "Carbon", "Disc", "Mavic Cosmic SL 65 Disc", 1649, 19);
        Wheel wheel101 = new Wheel("Mavic", "Carbon", "Disc", "Mavic Cosmic SL 45 Disc", 1555, 23);
        Wheel wheel102 = new Wheel("Mavic", "Carbon", "Disc", "Mavic Cosmic SL 32 Disc", 1475, 21);
        Wheel wheel103 = new Wheel("Mavic", "Carbon", "Disc", "Mavic Cosmic S 42 Disc", 1660, 21);
        Wheel wheel104 = new Wheel("Mavic", "Carbon", "Rim", "Mavic Cosmic S 40", 1764, 19);
        Wheel wheel105 = new Wheel("Mavic", "Carbon", "Rim", "Mavic Cosmic SL 40", 1600, 19);
        Wheel wheel106 = new Wheel("Shimano", "Carbon", "Disc", "Shimano WH-R9270-C36", 1154, 21);
        Wheel wheel107 = new Wheel("Vision", "Carbon", "Disc", "Vision Metron 60 SL Disc", 1490, 21);
        Wheel wheel108 = new Wheel("Vision", "Carbon", "Disc", "Vision Metron 30 SL Disc", 1370, 21);
        Wheel wheel109 = new Wheel("Vision", "Carbon", "Disc", "Vision Metron 40 SL Disc", 1420, 21);
        Wheel wheel110 = new Wheel("Vision", "Carbon", "Disc", "Vision Metron 45 SL Disc", 1390, 21);
        Wheel wheel111 = new Wheel("Vision", "Carbon", "Disc", "Vision Metron 37 SL Disc", 1290, 21);
        Wheel wheel112 = new Wheel("Vision", "Carbon", "Disc", "Vision Metron 81 SL Disc", 1660, 21);
        Wheel wheel113 = new Wheel("Vision", "Carbon", "Disc", "Vision Metron 55 SL Disc", 1540, 21);
        Wheel wheel114 = new Wheel("Reynolds", "Carbon", "Disc", "Reynolds Blacklabel 80 Expert", 1655, 21);
        Wheel wheel115 = new Wheel("Reynolds", "Carbon", "Disc", "Reynolds Blacklabel 60 Expert", 1540, 21);
        Wheel wheel116 = new Wheel("Reynolds", "Carbon", "Disc", "Reynolds Blacklabel 25 Expert", 1286, 21);
        Wheel wheel117 = new Wheel("Reynolds", "Carbon", "Disc", "Reynolds Blacklabel 46 Pro", 1397, 21);
        Wheel wheel118 = new Wheel("Reynolds", "Carbon", "Disc", "Reynolds Blacklabel 60 Pro", 1500, 21);
        Wheel wheel119 = new Wheel("DT Swiss", "Carbon", "Disc", "DT Swiss ERC 1100 DICUT 45", 1300, 25);
        Wheel wheel120 = new Wheel("Syncros", "Carbon", "Disc", "Capital SL Aero, 60mm", 1315, 25);
        Wheel wheel121 = new Wheel("Syncros", "Carbon", "Disc", "Capital SL, 40mm", 1170, 25);
        Wheel wheel122 = new Wheel("Syncros", "Carbon", "Disc", "Capital 1.0s Aero, 60mm", 1470, 25);
        Wheel wheel123 = new Wheel("Syncros", "Carbon", "Disc", "Capital 1.0s, 40mm", 1335, 25);
        Wheel wheel124 = new Wheel("Syncros", "Carbon", "Disc", "Capital 1.0 Aero, 60mm", 1630, 23);
        Wheel wheel125 = new Wheel("Syncros", "Carbon", "Disc", "Capital 1.0, 40mm", 1480, 25);
        Wheel wheel126 = new Wheel("Syncros", "Carbon", "Disc", "Capital 1.0, 35mm", 1574, 25);
        Wheel wheel127 = new Wheel("Syncros", "Carbon", "Disc", "Capital 1.0, 50mm", 1634, 25);
        Wheel wheel128 = new Wheel("Syncros", "Carbon", "Disc", "RP2.0, 50mm", 1770, 25);



        // Opret gear
        Gear gear1 = new Gear("Shimano", "Shimano Dura-Ace Di2 R9270", "Shimano Dura-Ace","Carbon", "Electronic", "Disc", 2579);
        Gear gear2 = new Gear("Shimano", "Shimano Dura-Ace Di2 R9170", "Shimano Dura-Ace", "Carbon", "Electronic", "Disc",2350);
        Gear gear3 = new Gear("Shimano", "Shimano Dura-Ace Di2 R9250", "Shimano Dura-Ace", "Carbon", "Electronic", "Rim",2300);
        Gear gear4 = new Gear("Shimano", "Shimano Dura-Ace Di2 R9200", "Shimano Dura-Ace", "Carbon", "Electronic", "Rim", 2300);
        Gear gear5 = new Gear("Shimano", "Shimano Dura-Ace R9200", "Shimano Dura-Ace", "Carbon", "Mechanical", "Rim", 2200);
        Gear gear6 = new Gear("Shimano", "Shimano Dura-Ace R9100", "Shimano Dura-Ace", "Carbon", "Mechanical", "Rim",2300);
        Gear gear7 = new Gear("Shimano", "Shimano Ultegra R8100", "Shimano Ultegra", "Carbon", "Mechanical", "Rim", 2716);
        Gear gear8 = new Gear("Shimano", "Shimano Ultegra R8000", "Shimano Ultegra", "Carbon", "Mechanical", "Rim", 2400);
        Gear gear9 = new Gear("Shimano", "Shimano Ultegra Di2 R8170", "Shimano Ultegra", "Carbon", "Electronic", "Disc", 2700);
        Gear gear10 = new Gear("Shimano", "Shimano Ultegra Di2 R8150", "Shimano Ultegra", "Carbon", "Electronic", "Rim",2600);
        Gear gear11 = new Gear("Shimano", "Shimano Ultegra Di2 R8100", "Shimano Ultegra", "Carbon", "Electronic", "Rim", 2600);
        Gear gear12 = new Gear("Shimano", "Shimano 105 Di2 R7170", "Shimano 105", "Aluminium", "Electronic", "Disc",3000);
        Gear gear45 = new Gear("Shimano", "Shimano 105 Di2 R7150", "Shimano 105", "Aluminium", "Electronic", "Rim",3000);
        Gear gear13 = new Gear("Shimano", "Shimano 105 R7100", "Shimano 105", "Aluminium", "Mechanical", "Rim",3026);
        Gear gear14 = new Gear("Shimano", "Shimano 105 R7000", "Shimano 105", "Aluminium", "Mechanical", "Rim", 2700);
        Gear gear15 = new Gear("Shimano", "Shimano Tiagra R4700", "Shimano Tiagra", "Aluminium", "Mechanical", "Rim", 2800);
        Gear gear16 = new Gear("Shimano", "Shimano Sora R3000", "Shimano Sora", "Aluminium", "Mechanical", "Rim", 3000);
        Gear gear17 = new Gear("Shimano", "Shimano Claris R2000", "Shimano Claris", "Aluminium", "Mechanical", "Rim", 3200);
        Gear gear18 = new Gear("Campagnolo", "Campagnolo Super Record EPS R12", "Campagnolo Super Record", "Carbon", "Electronic", "Disc", 2300);
        Gear gear19 = new Gear("Campagnolo", "Campagnolo Super Record R12", "Campagnolo Super Record", "Carbon", "Mechanical", "Rim", 2400);
        Gear gear20 = new Gear("Campagnolo", "Campagnolo Record EPS R12", "Campagnolo Record", "Carbon", "Electronic", "Disc", 2400);
        Gear gear21 = new Gear("Campagnolo", "Campagnolo Record R12", "Campagnolo Record", "Carbon", "Mechanical", "Rim", 2500);
        Gear gear22 = new Gear("Campagnolo", "Campagnolo Record 11-speed", "Campagnolo Record", "Carbon", "Mechanical", "Rim", 2400);
        Gear gear23 = new Gear("Campagnolo", "Campagnolo Chorus EPS R12", "Campagnolo Chorus", "Aluminium", "Electronic", "Rim", 2850);
        Gear gear24 = new Gear("Campagnolo", "Campagnolo Chorus R12", "Campagnolo Chorus", "Aluminium", "Mechanical", "Rim", 2850);
        Gear gear25 = new Gear("Campagnolo", "Campagnolo Athena EPS R11", "Campagnolo Athena", "Carbon", "Electronic", "Disc", 2800);
        Gear gear26 = new Gear("Campagnolo", "Campagnolo Athena R11", "Campagnolo Athena", "Aluminium", "Mechanical", "Rim", 2900);
        Gear gear27 = new Gear("Campagnolo", "Campagnolo Potenza R11", "Campagnolo Potenza", "Aluminium", "Mechanical", "Rim", 2550);
        Gear gear28 = new Gear("Campagnolo", "Campagnolo Centaur EPS R10", "Campagnolo Centaur", "Carbon", "Electronic", "Disc", 2650);
        Gear gear29 = new Gear("Campagnolo", "Campagnolo Centaur R10", "Campagnolo Centaur", "Aluminium", "Mechanical", "Rim", 2500);
        Gear gear30 = new Gear("Campagnolo", "Campagnolo Veloce R9", "Campagnolo Veloce", "Aluminium", "Mechanical", "Rim", 2400);
        Gear gear31 = new Gear("Campagnolo", "Campagnolo Mirage R8", "Campagnolo Mirage", "Aluminium", "Mechanical", "Rim", 1900);
        Gear gear32 = new Gear("Campagnolo", "Campagnolo Xenon 10", "Campagnolo Xenon",  "Aluminium", "Mechanical", "Rim", 2200);
        Gear gear33 = new Gear("Campagnolo", "Campagnolo C-Record", "Campagnolo C-Record", "Carbon", "Mechanical", "Rim", 1900);
        Gear gear34 = new Gear("SRAM", "SRAM Red AXS", "SRAM Red","Aluminium", "Electronic", "Disc", 2548);
        Gear gear35 = new Gear("SRAM", "SRAM Red eTap AXS", "SRAM Red", "Carbon", "Electronic", "Disc", 2650);
        Gear gear36 = new Gear("SRAM", "SRAM Red eTap 11-speed", "SRAM Red", "Carbon", "Electronic", "Disc", 2500);
        Gear gear37 = new Gear("SRAM", "SRAM Force eTap AXS", "SRAM Force", "Aluminium", "Electronic", "Disc", 2800);
        Gear gear38 = new Gear("SRAM", "SRAM Force AXS", "SRAM Force", "Aluminium", "Electronic", "Rim", 2600);
        Gear gear39 = new Gear("SRAM", "SRAM Force 22", "SRAM Force", "Aluminium", "Mechanical", "Rim", 2500);
        Gear gear40 = new Gear("SRAM", "SRAM Rival AXS", "SRAM Rival", "Aluminium", "Electronic", "Rim", 2400);
        Gear gear41 = new Gear("SRAM", "SRAM Rival 22", "SRAM Rival","Aluminium", "Mechanical", "Rim", 2200);
        Gear gear42 = new Gear("SRAM", "SRAM Rival 1", "SRAM Rival", "Aluminium", "Mechanical", "Disc", 2600);
        Gear gear43 = new Gear("SRAM", "SRAM Apex", "SRAM Apex", "Aluminium", "Mechanical", "Rim", 2750);
        Gear gear44 = new Gear("SRAM", "SRAM Apex 1", "SRAM Apex","Aluminium", "Mechanical", "Disc", 2800);


        try (EntityManager em = emf.createEntityManager()) {
            em.getTransaction().begin();

            // Gemmer rammer
            em.persist(frame1);
            em.persist(frame2);
            em.persist(frame3);
            em.persist(frame4);
            em.persist(frame5);
            em.persist(frame6);
            em.persist(frame7);
            em.persist(frame8);
            em.persist(frame9);
            em.persist(frame10);
            em.persist(frame11);
            em.persist(frame12);
            em.persist(frame13);
            em.persist(frame14);
            em.persist(frame15);
            em.persist(frame16);
            em.persist(frame17);
            em.persist(frame18);
            em.persist(frame19);
            em.persist(frame20);
            em.persist(frame21);
            em.persist(frame22);
            em.persist(frame23);
            em.persist(frame24);
            em.persist(frame25);
            em.persist(frame26);
            em.persist(frame27);
            em.persist(frame28);
            em.persist(frame29);
            em.persist(frame30);
            em.persist(frame31);
            em.persist(frame32);
            em.persist(frame33);
            em.persist(frame34);
            em.persist(frame35);
            em.persist(frame36);
            em.persist(frame37);
            em.persist(frame38);
            em.persist(frame39);
            em.persist(frame40);
            em.persist(frame41);
            em.persist(frame42);
            em.persist(frame43);
            em.persist(frame44);
            em.persist(frame45);
            em.persist(frame46);
            em.persist(frame47);
            em.persist(frame48);
            em.persist(frame49);
            em.persist(frame50);
            em.persist(frame51);
            em.persist(frame52);
            em.persist(frame53);
            em.persist(frame54);
            em.persist(frame55);
            em.persist(frame56);
            em.persist(frame57);
            em.persist(frame58);
            em.persist(frame59);
            em.persist(frame60);
            em.persist(frame61);
            em.persist(frame62);
            em.persist(frame63);
            em.persist(frame64);
            em.persist(frame65);
            em.persist(frame66);
            em.persist(frame67);
            em.persist(frame68);
            em.persist(frame69);
            em.persist(frame70);
            em.persist(frame71);
            em.persist(frame72);
            em.persist(frame73);
            em.persist(frame74);
            em.persist(frame75);
            em.persist(frame76);
            em.persist(frame77);
            em.persist(frame78);
            em.persist(frame79);
            em.persist(frame80);
            em.persist(frame81);
            em.persist(frame82);


            // Gemmer saddel
            em.persist(saddle1);
            em.persist(saddle2);
            em.persist(saddle3);
            em.persist(saddle4);
            em.persist(saddle5);
            em.persist(saddle6);
            em.persist(saddle7);
            em.persist(saddle8);
            em.persist(saddle9);
            em.persist(saddle10);
            em.persist(saddle11);
            em.persist(saddle12);
            em.persist(saddle13);
            em.persist(saddle14);
            em.persist(saddle15);
            em.persist(saddle16);
            em.persist(saddle17);
            em.persist(saddle18);
            em.persist(saddle19);
            em.persist(saddle20);
            em.persist(saddle21);
            em.persist(saddle22);
            em.persist(saddle23);
            em.persist(saddle24);
            em.persist(saddle25);
            em.persist(saddle26);
            em.persist(saddle27);
            em.persist(saddle28);
            em.persist(saddle29);
            em.persist(saddle30);
            em.persist(saddle31);
            em.persist(saddle32);
            em.persist(saddle33);
            em.persist(saddle34);
            em.persist(saddle35);
            em.persist(saddle36);
            em.persist(saddle37);
            em.persist(saddle38);
            em.persist(saddle39);
            em.persist(saddle40);
            em.persist(saddle41);
            em.persist(saddle42);
            em.persist(saddle43);
            em.persist(saddle44);
            em.persist(saddle45);
            em.persist(saddle46);
            em.persist(saddle47);
            em.persist(saddle48);
            em.persist(saddle49);
            em.persist(saddle50);
            em.persist(saddle51);
            em.persist(saddle52);
            em.persist(saddle53);
            em.persist(saddle54);
            em.persist(saddle55);
            em.persist(saddle56);
            em.persist(saddle57);
            em.persist(saddle58);
            em.persist(saddle59);
            em.persist(saddle60);
            em.persist(saddle61);
            em.persist(saddle62);
            em.persist(saddle63);
            em.persist(saddle64);
            em.persist(saddle65);
            em.persist(saddle66);
            em.persist(saddle67);
            em.persist(saddle68);
            em.persist(saddle69);
            em.persist(saddle70);
            em.persist(saddle71);
            em.persist(saddle72);
            em.persist(saddle73);
            em.persist(saddle74);
            em.persist(saddle75);
            em.persist(saddle76);
            em.persist(saddle77);
            em.persist(saddle78);
            em.persist(saddle79);
            em.persist(saddle80);
            em.persist(saddle81);
            em.persist(saddle82);
            em.persist(saddle83);
            em.persist(saddle84);
            em.persist(saddle85);
            em.persist(saddle86);
            em.persist(saddle87);
            em.persist(saddle88);
            em.persist(saddle89);
            em.persist(saddle90);
            em.persist(saddle91);
            em.persist(saddle92);
            em.persist(saddle93);
            em.persist(saddle94);
            em.persist(saddle95);
            em.persist(saddle96);
            em.persist(saddle97);
            em.persist(saddle98);
            em.persist(saddle99);
            em.persist(saddle100);
            em.persist(saddle101);
            em.persist(saddle102);
            em.persist(saddle103);
            em.persist(saddle104);
            em.persist(saddle105);
            em.persist(saddle106);
            em.persist(saddle107);
            em.persist(saddle108);
            em.persist(saddle109);
            em.persist(saddle110);
            em.persist(saddle111);
            em.persist(saddle112);
            em.persist(saddle113);
            em.persist(saddle114);
            em.persist(saddle115);
            em.persist(saddle116);
            em.persist(saddle117);


            // Gemmer hjul
            em.persist(wheel1);
            em.persist(wheel2);
            em.persist(wheel3);
            em.persist(wheel4);
            em.persist(wheel5);
            em.persist(wheel6);
            em.persist(wheel7);
            em.persist(wheel8);
            em.persist(wheel9);
            em.persist(wheel10);
            em.persist(wheel11);
            em.persist(wheel12);
            em.persist(wheel13);
            em.persist(wheel14);
            em.persist(wheel15);
            em.persist(wheel16);
            em.persist(wheel17);
            em.persist(wheel18);
            em.persist(wheel19);
            em.persist(wheel20);
            em.persist(wheel21);
            em.persist(wheel22);
            em.persist(wheel23);
            em.persist(wheel24);
            em.persist(wheel25);
            em.persist(wheel26);
            em.persist(wheel27);
            em.persist(wheel28);
            em.persist(wheel29);
            em.persist(wheel30);
            em.persist(wheel31);
            em.persist(wheel32);
            em.persist(wheel33);
            em.persist(wheel34);
            em.persist(wheel35);
            em.persist(wheel36);
            em.persist(wheel37);
            em.persist(wheel38);
            em.persist(wheel39);
            em.persist(wheel40);
            em.persist(wheel41);
            em.persist(wheel42);
            em.persist(wheel43);
            em.persist(wheel44);
            em.persist(wheel45);
            em.persist(wheel46);
            em.persist(wheel47);
            em.persist(wheel48);
            em.persist(wheel49);
            em.persist(wheel50);
            em.persist(wheel51);
            em.persist(wheel52);
            em.persist(wheel53);
            em.persist(wheel54);
            em.persist(wheel55);
            em.persist(wheel56);
            em.persist(wheel57);
            em.persist(wheel58);
            em.persist(wheel59);
            em.persist(wheel60);
            em.persist(wheel61);
            em.persist(wheel62);
            em.persist(wheel63);
            em.persist(wheel64);
            em.persist(wheel65);
            em.persist(wheel66);
            em.persist(wheel67);
            em.persist(wheel68);
            em.persist(wheel69);
            em.persist(wheel70);
            em.persist(wheel71);
            em.persist(wheel72);
            em.persist(wheel73);
            em.persist(wheel74);
            em.persist(wheel75);
            em.persist(wheel76);
            em.persist(wheel77);
            em.persist(wheel78);
            em.persist(wheel79);
            em.persist(wheel80);
            em.persist(wheel81);
            em.persist(wheel82);
            em.persist(wheel83);
            em.persist(wheel84);
            em.persist(wheel85);
            em.persist(wheel86);
            em.persist(wheel87);
            em.persist(wheel88);
            em.persist(wheel89);
            em.persist(wheel90);
            em.persist(wheel91);
            em.persist(wheel92);
            em.persist(wheel93);
            em.persist(wheel94);
            em.persist(wheel95);
            em.persist(wheel96);
            em.persist(wheel97);
            em.persist(wheel98);
            em.persist(wheel99);
            em.persist(wheel100);
            em.persist(wheel101);
            em.persist(wheel102);
            em.persist(wheel103);
            em.persist(wheel104);
            em.persist(wheel105);
            em.persist(wheel106);
            em.persist(wheel107);
            em.persist(wheel108);
            em.persist(wheel109);
            em.persist(wheel110);
            em.persist(wheel111);
            em.persist(wheel112);
            em.persist(wheel113);
            em.persist(wheel114);
            em.persist(wheel115);
            em.persist(wheel116);
            em.persist(wheel117);
            em.persist(wheel118);
            em.persist(wheel119);
            em.persist(wheel120);
            em.persist(wheel121);
            em.persist(wheel122);
            em.persist(wheel123);
            em.persist(wheel124);
            em.persist(wheel125);
            em.persist(wheel126);
            em.persist(wheel127);
            em.persist(wheel128);




            // Gemmer gear
            em.persist(gear1);
            em.persist(gear2);
            em.persist(gear3);
            em.persist(gear4);
            em.persist(gear5);
            em.persist(gear6);
            em.persist(gear7);
            em.persist(gear8);
            em.persist(gear9);
            em.persist(gear10);
            em.persist(gear11);
            em.persist(gear12);
            em.persist(gear13);
            em.persist(gear14);
            em.persist(gear15);
            em.persist(gear16);
            em.persist(gear17);
            em.persist(gear18);
            em.persist(gear19);
            em.persist(gear20);
            em.persist(gear21);
            em.persist(gear22);
            em.persist(gear23);
            em.persist(gear24);
            em.persist(gear25);
            em.persist(gear26);
            em.persist(gear27);
            em.persist(gear28);
            em.persist(gear29);
            em.persist(gear30);
            em.persist(gear31);
            em.persist(gear32);
            em.persist(gear33);
            em.persist(gear34);
            em.persist(gear35);
            em.persist(gear36);
            em.persist(gear37);
            em.persist(gear38);
            em.persist(gear39);
            em.persist(gear40);
            em.persist(gear41);
            em.persist(gear42);
            em.persist(gear43);
            em.persist(gear44);



            // Opretter cykler og tilføjer komponenter
            Bicycle bicycle1 = new Bicycle("Trek", "Domane SL6", 56, 3500, 9.3, "Endurance road bike", frame66, gear1, wheel41, saddle41);
            Bicycle bicycle2 = new Bicycle("Canyon", "Ultimate CF SLX 9 Di2", 54, 9000, 6.8, "Lightweight racing bike", frame24, gear6, wheel106, saddle82);
            Bicycle bicycle3 = new Bicycle("Pinarello", "Dogma F12", 58, 10500, 7.6, "Aero road bike", frame47, gear26, wheel42, saddle1);
            Bicycle bicycle4 = new Bicycle("Giant", "TCR Advanced", 55, 3200, 7.8, "Endurance race bike", frame36, gear1, wheel2, saddle5);
            Bicycle bicycle5 = new Bicycle("Bianchi", "Oltre XR4", 57, 6000, 7.0, "Road bike", frame9, gear1, wheel24, saddle1);
            Bicycle bicycle6 = new Bicycle("Specialized", "S-Works Tarmac SL7", 56, 8000, 6.7, "Ultra-lightweight race bike", frame61, gear3, wheel84, saddle1);
            Bicycle bicycle7 = new Bicycle("Colnago", "C64", 58, 7000, 7.2, "Road bike", frame78, gear21, wheel64, saddle5);
            Bicycle bicycle8 = new Bicycle("Cannondale", "SuperSix EVO", 54, 4000, 7.5, "Aero road bike", frame16, gear3, wheel107, saddle5);
            Bicycle bicycle9 = new Bicycle("Felt", "FR FRD", 55, 6000, 6.9, "Road bike", frame31, gear2, wheel2, saddle1);
            Bicycle bicycle10 = new Bicycle("Scott", "Foil RC", 56, 5500, 7.6, "Aero Road bike", frame55, gear1, wheel1, saddle5);
            Bicycle bicycle11 = new Bicycle("Canyon", "Aeroad CF SLX", 56, 4400, 7.3, "Aerodynamic road bike", frame17, gear1, wheel54, saddle82);
            Bicycle bicycle12 = new Bicycle("Trek", "Madone SLR 9", 58, 8500, 7.7, "Lightweight and aerodynamic", frame66, gear3, wheel1, saddle1);
            Bicycle bicycle13 = new Bicycle("BMC", "Teammachine SLR01", 56, 7000, 6.5, "Aero road bike", frame10, gear1, wheel1, saddle5);
            Bicycle bicycle14 = new Bicycle("Giant", "Defy Advanced", 55, 3000, 7.9, "Endurance bike", frame37, gear6, wheel3, saddle4);
            Bicycle bicycle15 = new Bicycle("BMC", "Teammachine SLR01", 56, 7000, 6.5, "Aero road bike", frame10, gear1, wheel1, saddle5);
            Bicycle bicycle16 = new Bicycle("Cervélo", "R5", 58, 6500, 7.1, "Lightweight", frame25, gear1, wheel1, saddle6);
            Bicycle bicycle17 = new Bicycle("Canyon", "Ultimate CF SL", 54, 2500, 8.5, "Lightweight", frame23, gear1, wheel1, saddle7);
            Bicycle bicycle18 = new Bicycle("Trek", "Emonda SL", 55, 2800, 7.8, "Lightweight", frame67, gear1, wheel1, saddle8);
            Bicycle bicycle19 = new Bicycle("Specialized", "Allez Sprint", 56, 2000, 8.2, "Lightweight", frame59, gear1, wheel1, saddle9);
            Bicycle bicycle20 = new Bicycle("Giant", "Contend", 58, 1500, 8.7, "Lightweight", frame71, gear1, wheel1, saddle10);
            Bicycle bicycle21 = new Bicycle("BMC", "Roadmachine", 56, 3500, 7.5, "Lightweight", frame11, gear1, wheel1, saddle11);
            Bicycle bicycle22 = new Bicycle("Cervélo", "R3", 56, 4800, 7.0, "Versatile racing bike", frame26, gear2, wheel1, saddle6);
            Bicycle bicycle23 = new Bicycle("Colnago", "V3Rs Disc", 56, 8000, 6.9, "Aero road bike", frame74, gear2, wheel1, saddle6);
            Bicycle bicycle24 = new Bicycle("Cervélo", "S3", 56, 5500, 6.4, "Aero road bike", frame15, gear2, wheel1, saddle5);
            Bicycle bicycle25 = new Bicycle("Colnago", "C59", 58, 6400, 6.5, "Road bike", frame28, gear1, wheel1, saddle1);
            Bicycle bicycle26 = new Bicycle("Colnago", "C64 Disc", 56, 7900, 7.0, "Premium road bike", frame29, gear2, wheel1, saddle23);
            Bicycle bicycle27 = new Bicycle("Cervélo", "S5", 54, 6500, 6.6, "Aero road bike", frame72, gear2, wheel1, saddle5);
            Bicycle bicycle28 = new Bicycle("Pinarello", "F10", 54, 7500, 6.7, "Aero road bike", frame73, gear2, wheel1, saddle5);
            Bicycle bicycle29 = new Bicycle("Pinarello", "Paris", 56, 5900, 7.3, "Touring bike", frame48, gear1, wheel1, saddle9);
            Bicycle bicycle30 = new Bicycle("Scott", "Addict RC", 56, 6200, 7.0, "Performance road bike", frame54, gear1, wheel1, saddle2);
            Bicycle bicycle31 = new Bicycle("Canyon", "Endurace CFR Di2", 55, 3200, 7.8, "Endurance road bike", frame21, gear6, wheel119, saddle4);
            Bicycle bicycle32 = new Bicycle("Giant", "Defy Advanced Pro", 55, 4200, 7.1, "Endurance bike", frame37, gear3, wheel1, saddle6);
            Bicycle bicycle33 = new Bicycle("Felt", "F5", 56, 2900, 8.2, "Lightweight racing bike", frame32, gear1, wheel2, saddle6);
            Bicycle bicycle34 = new Bicycle("Giant", "Defy", 55, 3300, 7.5, "Endurance bike", frame37, gear3, wheel2, saddle4);
            Bicycle bicycle35 = new Bicycle("Bianchi", "Impulso", 56, 2900, 7.9, "Versatile road bike", frame8, gear3, wheel1, saddle6);
            Bicycle bicycle36 = new Bicycle("Specialized", "Roubaix", 58, 5000, 6.9, "Endurance road bike", frame57, gear1, wheel1, saddle2);
            Bicycle bicycle37 = new Bicycle("Felt", "VR FRD", 55, 4200, 7.2, "Endurance road bike", frame31, gear2, wheel2, saddle3);
            Bicycle bicycle38 = new Bicycle("Pinarello", "Dogma F7", 58, 6000, 7.6, "Aero road bike", frame47, gear1, wheel42, saddle1);
            Bicycle bicycle39 = new Bicycle("Giant", "TCR Advanced Pro", 54, 4000, 7.8, "Lightweight racing bike", frame36, gear1, wheel2, saddle2);
            Bicycle bicycle40 = new Bicycle("Bianchi", "Oltre XR3", 57, 4800, 7.4, "Aero road bike", frame9, gear2, wheel1, saddle1);
            Bicycle bicycle41 = new Bicycle("Specialized", "S-Works Tarmac SL6", 56, 8000, 6.7, "Aero road bike", frame61, gear1, wheel1, saddle1);
            Bicycle bicycle42 = new Bicycle("De Rosa", "Merak Grafite Disc", 56, 6000, 6.7, "Aero road bike", frame76, gear1, wheel44, saddle42);
            Bicycle bicycle45 = new Bicycle("De Rosa", "Settanta Carbon Disc", 56, 7000, 6.7, "Aero road bike", frame75, gear1, wheel44, saddle42);
            Bicycle bicycle46 = new Bicycle("De Rosa", "Idol Red Grade Disc", 56, 6100, 6.7, "Aero road bike", frame77, gear1, wheel44, saddle42);
            Bicycle bicycle47 = new Bicycle("De Rosa", "838 Rosso Rosso Disc", 56, 3100, 7.2, "Aero road bike", frame1, gear11, wheel46, saddle43);
            Bicycle bicycle48 = new Bicycle("Giant", "Defy Advanced", 55, 3000, 7.9, "Endurance bike", frame37, gear6, wheel3, saddle4);
            Bicycle bicycle49 = new Bicycle("Scott", "Addict RC Ultimate", 56, 13500, 6.7, "Lightweight road bike", frame55, gear35, wheel88, saddle113);
            Bicycle bicycle50 = new Bicycle("Scott", "Foil RC Ultimate", 56, 16000, 7.2, "Aero Road bike", frame55, gear12, wheel124, saddle104);
            Bicycle bicycle51 = new Bicycle("Scott", "Foil RC Pro", 56, 11100, 7.3, "Aero Road bike", frame80, gear1, wheel21, saddle108);
            Bicycle bicycle52 = new Bicycle("Scott", "Foil RC 10", 56, 6930, 7.9, "Aero Road bike", frame80, gear10, wheel124, saddle115);
            Bicycle bicycle53 = new Bicycle("Scott", "Foil RC 20", 56, 6000, 8.4, "Aero Road bike", frame80, gear40, wheel127, saddle104);
            Bicycle bicycle54 = new Bicycle("Scott", "Foil RC 30", 56, 5330, 8.5, "Aero Road bike", frame55, gear12, wheel124, saddle104);
            Bicycle bicycle55 = new Bicycle("Scott", "Addict RC Ultimate", 56, 14670, 6.7, "Aero Road bike", frame55, gear1, wheel1, saddle5);
            Bicycle bicycle56 = new Bicycle("Scott", "Addict RC Pro", 56, 9600, 7.2, "Aero Road bike", frame79, gear1, wheel23, saddle107);
            Bicycle bicycle57 = new Bicycle("Scott", "Addict RC 10", 56, 6930, 7.9, "Aero Road bike", frame55, gear1, wheel1, saddle5);
            Bicycle bicycle58 = new Bicycle("Scott", "Addict RC 15", 56, 6670, 7.6, "Aero Road bike", frame80, gear10, wheel126, saddle114);
            Bicycle bicycle59 = new Bicycle("Scott", "Addict RC 20", 56, 5330, 7.6, "Aero Road bike", frame80, gear10, wheel125, saddle114);
            Bicycle bicycle60 = new Bicycle("Scott", "Addict RC 30", 56, 5330, 7.7, "Aero Road bike", frame80, gear40, wheel125, saddle114);
            Bicycle bicycle61 = new Bicycle("Scott", "Addict RC 40", 56, 4800, 7.6, "Aero Road bike", frame80, gear45, wheel128, saddle114);
            Bicycle bicycle62 = new Bicycle("Scott", "Addict 10", 56, 4000, 8.7, "Aero Road bike", frame82, gear40, wheel128, saddle112);
            Bicycle bicycle63 = new Bicycle("Scott", "Addict 20", 56, 3600, 8.7, "Aero Road bike", frame82, gear45, wheel128, saddle112);
            Bicycle bicycle64 = new Bicycle("Scott", "Addict 30", 56, 2935, 8.6, "Aero Road bike", frame82, gear14, wheel128, saddle112);





            em.persist(bicycle1);
            em.persist(bicycle2);
            em.persist(bicycle3);
            em.persist(bicycle4);
            em.persist(bicycle5);
            em.persist(bicycle6);
            em.persist(bicycle7);
            em.persist(bicycle8);
            em.persist(bicycle9);
            em.persist(bicycle10);
            em.persist(bicycle11);
            em.persist(bicycle12);
            em.persist(bicycle13);
            em.persist(bicycle14);
            em.persist(bicycle15);
            em.persist(bicycle16);
            em.persist(bicycle17);
            em.persist(bicycle18);
            em.persist(bicycle19);
            em.persist(bicycle20);
            em.persist(bicycle21);
            em.persist(bicycle22);
            em.persist(bicycle23);
            em.persist(bicycle24);
            em.persist(bicycle25);
            em.persist(bicycle26);
            em.persist(bicycle27);
            em.persist(bicycle28);
            em.persist(bicycle29);
            em.persist(bicycle30);
            em.persist(bicycle31);
            em.persist(bicycle32);
            em.persist(bicycle33);
            em.persist(bicycle34);
            em.persist(bicycle35);
            em.persist(bicycle36);
            em.persist(bicycle37);
            em.persist(bicycle38);
            em.persist(bicycle39);
            em.persist(bicycle40);
            em.persist(bicycle41);
            em.persist(bicycle42);
            em.persist(bicycle45);
            em.persist(bicycle46);
            em.persist(bicycle47);
            em.persist(bicycle48);
            em.persist(bicycle49);
            em.persist(bicycle50);
            em.persist(bicycle51);
            em.persist(bicycle52);
            em.persist(bicycle53);
            em.persist(bicycle54);
            em.persist(bicycle55);
            em.persist(bicycle56);
            em.persist(bicycle57);
            em.persist(bicycle58);
            em.persist(bicycle59);
            em.persist(bicycle60);
            em.persist(bicycle61);
            em.persist(bicycle62);
            em.persist(bicycle63);
            em.persist(bicycle64);







            em.getTransaction().commit();
        } catch (Exception e) {
            e.printStackTrace();
            throw new RuntimeException("Error populating database", e);
        }
    }

}
